name: PR Gate (Fast Security)
on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read

defaults:
  run:
    working-directory: ./paybox-stdd-starter  # <-- your app folder

jobs:
  pr-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug layout
        run: |
          pwd
          ls -la
          test -f package.json || (echo "No package.json here" && exit 1)

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # IMPORTANT: path(s) are relative to the repo root, not the working-directory
          cache-dependency-path: |
            paybox-stdd-starter/package-lock.json

      - run: npm ci --include=dev
      - run: npx jest --version
      - run: npm run test:sec

      - name: Semgrep (curated)
        uses: returntocorp/semgrep-action@v1
        with: { config: ./.semgrep/semgrep.yml }

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git -v --redact --config=.gitleaks.toml
