# .github/workflows/pr-gate.yml
name: PR Gate (Fast Security)
on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read

# 1) Make sure we run in the app folder (change path if yours is different)
defaults:
  run:
    working-directory: ./paybox-stdd-starter

jobs:
  pr-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./paybox-stdd-starter/package-lock.json

      # Debug: prove we're in the right folder
      - run: pwd && ls -la && test -f package.json || (echo "No package.json here" && exit 1)

      # 2) Install *dev* deps (where Jest is)
      - run: npm ci --include=dev

      # Debug: show that jest is installed
      - run: npx jest --version

      # 3) Run your full security test pack
      - run: npm run test:sec

      - name: Semgrep (curated)
        uses: returntocorp/semgrep-action@v1
        with:
          config: ./.semgrep/semgrep.yml

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git -v --redact --config=.gitleaks.toml
